<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * AirportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirportRepository extends \Doctrine\ORM\EntityRepository
{
}
