<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * CancelationProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CancelationProductRepository extends \Doctrine\ORM\EntityRepository
{
}
