<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * CarClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarClassRepository extends \Doctrine\ORM\EntityRepository
{
}
