<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * CarCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
