<?php

namespace Daiquiri\AdminBundle\Entity;

use \Doctrine\Common\Collections\ArrayCollection;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository {

    function findCarByCapacity($collection = array(), $capacity = null) {
        $salida = array();
        if (count($collection) > 0) {
            foreach ($collection as $element) {
                if ($element->getCapacity() == $capacity) {
                    $salida [] = $element;
                }
            }
        }
        return $salida;
    }

    function findCarByLuggageCapacity($collection = array(), $luggagecapacity = null) {
        $salida = array();
        if (count($collection) > 0) {
            foreach ($collection as $element) {
                if ($element->getLuggageCapacity()->getId() == $luggagecapacity->getId()) {
                    $salida [] = $element;
                }
            }
        }
        return $salida;
    }

   

}
