<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * ChainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChainRepository extends \Doctrine\ORM\EntityRepository
{
}
