<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * CircuitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircuitRepository extends \Doctrine\ORM\EntityRepository {

    public function isAvailableinDate(Circuit $circuit, \DateTime $date) {
        $r = $this->getEntityManager()
                ->createQuery('SELECT c FROM DaiquiriAdminBundle:Circuit c JOIN c.circuit_availabilitys a WHERE c.id = :circuit_id AND a.date = :date')
                ->setParameter('date', $date->format('Y-m-d'))
                ->setParameter('circuit_id', $circuit->getId())
                ->getResult();
        if (count($r) > 0) {
            return $r;
        } else {
            return null;
        }
    }
    public function getCountAllowedKids(){
       $em = $this->getEntityManager()
           ->createQuery("
           SELECT count(circuitos) as allowkids from DaiquiriAdminBundle:Circuit circuitos
            where circuitos.allowkid=TRUE

           ")
           ->getResult();
if (count($em) > 0) {
    return $em;
} else {
    return null;
}


/*//        $dql = " SELECT (count(circuits)
// FROM DaiquiriAdminBundle:Circuit circuits
// where circuits.allowkids = TRUE) as countAllow,
// (count(circuits)
// FROM DaiquiriAdminBundle:Circuit circuits
// where circuits.allowkids = FALSE ) as countNotAllow";
//        $query = $this->getEntityManager()->createQuery($dql)
//            ->getResult();
//
//        return $query;*/
    }
    public function getNotAllowedKids() {
        $em = $this->getEntityManager()
            ->createQuery("
           SELECT count(circuitos) as notallowkids from DaiquiriAdminBundle:Circuit circuitos
            where circuitos.allowkid=FALSE

           ")
            ->getResult();
        if (count($em) > 0) {
            return $em;
        } else {
            return null;
        }

    }


}
