<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * CircuitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircuitRepository extends \Doctrine\ORM\EntityRepository {

    public function isAvailableinDate(Circuit $circuit, \DateTime $date) {
        $r = $this->getEntityManager()
                ->createQuery('SELECT c FROM DaiquiriAdminBundle:Circuit c JOIN c.circuit_availabilitys a WHERE c.id = :circuit_id AND a.date = :date')
                ->setParameter('date', $date->format('Y-m-d'))
                ->setParameter('circuit_id', $circuit->getId())
                ->getResult();
        if (count($r) > 0) {
            return $r;
        } else {
            return null;
        }
    }

}
