<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * CircuitDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircuitDayRepository extends \Doctrine\ORM\EntityRepository
{
}
