<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * CircuitAvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircuitAvailabilityRepository extends \Doctrine\ORM\EntityRepository
{
}
