<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * ContactCauseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactCauseRepository extends \Doctrine\ORM\EntityRepository
{
}
