<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * DUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DUserRepository extends \Doctrine\ORM\EntityRepository
{
}
