<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * ExcursionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcursionRepository extends \Doctrine\ORM\EntityRepository
{
}
