<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * ExcursionColectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcursionColectiveRepository extends \Doctrine\ORM\EntityRepository
{
}
