<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * ExcursionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcursionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
