<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * ExcursionExclusiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcursionExclusiveRepository extends \Doctrine\ORM\EntityRepository
{
}
