<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * HotelTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getHotelsTypes(){
        $dql = "SELECT ht as type,
                  (SELECT count(hoteles) FROM DaiquiriAdminBundle:Hotel hoteles where hoteles.hotelType = ht) as cantType            
                FROM DaiquiriAdminBundle:HotelType ht";

        $query = $this->getEntityManager()->createQuery($dql)
            ->getResult();

        return $query;
    }
}
