<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * HotelFacilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelFacilityRepository extends \Doctrine\ORM\EntityRepository
{
}
