<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * HotelFacilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelFacilityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getHotelsFacilities(){
        $dql = "SELECT DISTINCT hf.title as facility,
                  (SELECT count(hf2) FROM DaiquiriAdminBundle:HotelFacility hf2 where hf2.title = hf.title) as cantTypeFacility            
                FROM DaiquiriAdminBundle:HotelFacility hf";
        $query = $this->getEntityManager()->createQuery($dql)
            ->getResult();
        return $query;
    }


    public function getCountByFacility($facility){


    }
}
