<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * HotelFacilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelFacilityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getHotelsFacilities(){
        $dql = "SELECT DISTINCT ht.title as facility,
                  (SELECT count(hoteles) FROM DaiquiriAdminBundle:Hotel hoteles where hoteles.hotelIdFacility = ht) as cantTypeFacility            
                FROM DaiquiriAdminBundle:HotelFacility ht";

        $query = $this->getEntityManager()->createQuery($dql)
            ->getResult();

        return $query;
    }
}
