<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * HotelTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
