<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * HotelSalesAgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelSalesAgentRepository extends \Doctrine\ORM\EntityRepository
{
}
