<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * LuggageCapacityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LuggageCapacityRepository extends \Doctrine\ORM\EntityRepository
{
}
