<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * MedicalProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalProgramRepository extends \Doctrine\ORM\EntityRepository
{
}
