<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * MedicalServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
