<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * OcupationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OcupationRepository extends \Doctrine\ORM\EntityRepository
{
}
