<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * PackageOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
