<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * PoloReposito$parary
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoloRepository extends \Doctrine\ORM\EntityRepository {

    public function getAllDiferentWithTransfer() {
        $r = $this->getEntityManager()
                ->createQuery('SELECT DISTINCT p FROM DaiquiriAdminBundle:Polo p JOIN p.places pl JOIN pl.transfers_from')
                ->getResult();
        return $r;
    }
    
    public function getAllDiferentPoloWithHotel() {
        $r = $this->getEntityManager()
                ->createQuery('SELECT h FROM DaiquiriAdminBundle:Hotel h JOIN h.polo p GROUP BY p' )
                ->getResult();
        return $r;
    }
    public function getPolos(){
        $dql = "SELECT DISTINCT polo as TYPE,
                  (SELECT count(c) FROM DaiquiriAdminBundle:Circuit c where c.polofrom = polo) as cantPolo
                FROM DaiquiriAdminBundle:Polo polo";

       /* $dql = "SELECT DISTINCT pol.title as polo,
                  (SELECT count(c) FROM DaiquiriAdminBundle:Circuit c where c.poloFrom = pol.) as cantPolo
                FROM DaiquiriAdminBundle:Polo pol";*/

        $query = $this->getEntityManager()->createQuery($dql)
            ->getResult();
        return $query;
    }

}
