<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * PoloReposito$parary
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoloRepository extends \Doctrine\ORM\EntityRepository {

    public function getAllDiferentWithTransfer() {
        $r = $this->getEntityManager()
                ->createQuery('SELECT DISTINCT p FROM DaiquiriAdminBundle:Polo p JOIN p.places pl JOIN pl.transfers_from')
                ->getResult();
        return $r;
    }
    
    public function getAllDiferentPoloWithHotel() {
        $r = $this->getEntityManager()
                ->createQuery('SELECT h FROM DaiquiriAdminBundle:Hotel h JOIN h.polo p GROUP BY p' )
                ->getResult();
        return $r;
    }

}
