<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * ProductIncrementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductIncrementRepository extends \Doctrine\ORM\EntityRepository
{
}
