<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * ProductSeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSeoRepository extends \Doctrine\ORM\EntityRepository
{
}
