<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * RentalHouseRoomFacilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalHouseRoomFacilityRepository extends \Doctrine\ORM\EntityRepository
{
}
