<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * RentalHouseFacilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalHouseFacilityRepository extends \Doctrine\ORM\EntityRepository
{
}
