<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * RentalHouseRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalHouseRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
