<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * RentalHouseOwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalHouseOwnerRepository extends \Doctrine\ORM\EntityRepository
{
}
