<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * RentalHouseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalHouseTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
