<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * RentalHouseAvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalHouseRoomAvailabilityRepository extends \Doctrine\ORM\EntityRepository
{
}
