<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * RoomAvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomAvailabilityRepository extends \Doctrine\ORM\EntityRepository
{
}
