<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * SuplementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuplementRepository extends \Doctrine\ORM\EntityRepository
{
}
