<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * ExclusiveTransferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferExclusiveRepository extends \Doctrine\ORM\EntityRepository
{
}
