<?php

namespace Daiquiri\AdminBundle\Entity;

/**
 * ColectiveTransferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferColectiveRepository extends \Doctrine\ORM\EntityRepository
{
}
