<?php

namespace Daiquiri\ReservationBundle\Entity;

/**
 * ConfigurationPamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationPamRepository extends \Doctrine\ORM\EntityRepository
{
}
