<?php

namespace Daiquiri\AdminBundle\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Route\RouteCollection;

class PackageAdmin extends AbstractAdmin {

    protected function configureRoutes(RouteCollection $collection) {
        $collection->add('form-package-option-item', 'form-package-option-item');
        $collection->add('find-package-option-searcher', 'find-package-option-searcher');
        $collection->add('add-to-cart', 'add-to-cart');

        
    }

    public function getTemplate($name) {
        switch ($name) {
            case 'list':
                return 'DaiquiriAdminBundle:Package:package_base_list.html.twig';
                break;
            default:
                return parent::getTemplate($name); // TODO: Change the autogenerated stub
                break;
        }
    }

    protected function configureFormFields(FormMapper $formMapper) {
        $formMapper
                ->add('title', 'text', array('label' => 'Package Name'))
                ->add('description', 'sonata_simple_formatter_type', array(
                    'label' => 'Package Description',
                    'format' => 'richhtml',
                    'required' => false
                ))
                ->add('picture', 'sonata_media_type', array(
                    'provider' => 'sonata.media.provider.image',
                    'context' => 'daiquiri'
                ))
                ->add('gallery', 'sonata_type_model_list', array('required' => false), array(
                    'provider' => 'sonata.media.provider.image',
                    'context' => 'daiquiri'
                ))
                ->end()
                ->with('Package Options')
                ->add('package_options', 'sonata_type_model', array(
                    'class' => 'Daiquiri\AdminBundle\Entity\PackageOption',
                    'property' => 'title',
                    'multiple' => true
                ))
                /* ->add('package_options', 'sonata_type_collection', array('label' => 'Option')) */
                ->end()
                ->end()
                ->with('Locale Block')
                ->add('locale', 'language', array(
                    'preferred_choices' => array('en', 'es', 'it' )
                ))
                ->end()
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper) {
        $datagridMapper
                ->add('title', null, array('label' => 'Package Name'))
        ;
    }

    protected function configureListFields(ListMapper $listMapper) {
        $listMapper
                ->add('picture', 'string', array('template' => 'SonataMediaBundle:MediaAdmin:list_image.html.twig'))
                ->addIdentifier('title')
                ->add('description', 'html', array(
                    'truncate' => array(
                        'separator' => ' ...',
                        'label' => 'Package Description'
                    )
                ))
                ->add('gallery')
                ->add('_action', 'actions', array(
                    'actions' => array(
                        'edit' => array(),
                        'delete' => array(),
                        'apply' => array(
                            'template' => 'DaiquiriReservationBundle:Package:request_buttom.html.twig'
                        ),
                       
                    )
                ))
        ;
    }

    public function prePersist($package) {
        $this->preUpdate($package);
    }

    public function preUpdate($package) {
        $package->setPackageOptions($package->getPackageOptions());
    }

    public $supportsPreviewMode = true;

}
