<?php

namespace Daiquiri\AdminBundle\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Route\RouteCollection as RouteCollection;

class SeasonAdmin extends AbstractAdmin {
    /**
     * @param RouteCollection $collection
     * @return Response|void
     */
    protected function configureRoutes(RouteCollection $collection)
    {
        $collection->add('form-create-season-for-all-hotel-by-chain', 'formCreateSeasonForAllHotelByChain');
        $collection->add('create-season-for-all-hotel-by-chain', 'createSeasonForAllHotelByChain');
      
    }
    /**
     * @param string $name
     * @return null|string
     */
    public function getTemplate($name)
    {
        switch ($name) {
            case 'list':
                return 'DaiquiriAdminBundle:Season:season_base_list.html.twig';                
                break;            
            default:
                return parent::getTemplate($name); // TODO: Change the autogenerated stub
                break;
        }
    }

    protected function configureFormFields(FormMapper $formMapper) {
        $formMapper
                ->add('title', 'text', array('label' => 'Season Name'))
                ->add('description', 'sonata_simple_formatter_type', array(
                    'label' => 'Season Description',
                    'format' => 'richhtml',
                    'required'=>false
                ))
                ->add('startdate', 'sonata_type_date_picker', array('label' => 'Start Date'))
                ->add('enddate', 'sonata_type_date_picker', array('label' => 'End Date'))
                ->end()
                ->with('Locale Block')
                ->add('locale', 'language', array(
                    'preferred_choices' => array('en', 'es', 'it' )
                ))
                ->end()
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper) {
        $datagridMapper
                ->add('title', null, array('label' => 'Season Name'))
                ->add('startdate', 'doctrine_orm_datetime_range', array('field_type' => 'sonata_type_datetime_range_picker'))
                ->add('enddate', 'doctrine_orm_datetime_range', array('field_type' => 'sonata_type_datetime_range_picker'))
                ->add('hotel')
                
                ->add('room_season_ocupation_prices', null, array('label' => 'Room Name'))


        ;
    }

    protected function configureListFields(ListMapper $listMapper) {
        $listMapper
                ->add('startdate', null, array('label' => 'Start Date', 'editable' => true))
                ->add('enddate', null, array('label' => 'End Date', 'editable' => true))
                ->add('hotel')
                ->add('_action', 'actions', array(
                    'actions' => array(
                        'edit' => array(),
                        'delete' => array(),
                    )
                ))
        ;
    }

    public function prePersist($season) {
        $this->preUpdate($season);
    }

  
    public $supportsPreviewMode = true;

}
