<?php

namespace Daiquiri\AdminBundle\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Route\RouteCollection as RouteCollection;

class TransferExclusiveAdmin extends AbstractAdmin {

    public $routeitem = 'form-transfer-exclusive-searcher';

    /**
     * @param RouteCollection $collection
     * @return Response|void
     */
    protected function configureRoutes(RouteCollection $collection) {
        $collection->add('form-create-transfer-exclusive-by-polo-and-type', 'formCreateTransferExclusiveByPoloAndType');
        $collection->add('create-transfer-exclusive-by-polo-and-type', 'CreateTransferExclusiveByPoloAndType');
        $collection->add('form-transfer-exclusive-searcher', $this->getRouterIdParameter() . '/form-transfer-searcher');
        $collection->add('find-transfer-exclusive-searcher', $this->getRouterIdParameter() . '/find-transfer-searcher');
        $collection->add('addtocart', 'add-to-cart');
       
    }

    /**
     * @param string $name
     * @return null|string
     */
    public function getTemplate($name) {
        switch ($name) {
            case 'list':
                return 'DaiquiriAdminBundle:TransferExclusive:transfer_exclusive_base_list.html.twig';
                break;
            default:
                return parent::getTemplate($name); // TODO: Change the autogenerated stub
                break;
        }
    }

    protected function configureFormFields(FormMapper $formMapper) {
        $formMapper
                ->with("Place Origin", array('class' => 'col-md-4'))
                ->add('placefrom', 'sonata_type_model', array(
                    'class' => 'Daiquiri\AdminBundle\Entity\Place',
                    'property' => 'title',
                    'label' => 'Place From'
                ))
                ->add('starttime', 'sonata_type_datetime_picker', array(
                    'label' => 'Pick-up Time',
                    'attr' => array('class' => 'form-control'),
                    'required' => false))
                ->end()
                ->end()
                ->with("Place Destination", array('class' => 'col-md-4'))
                ->add('placeto', 'sonata_type_model', array(
                    'class' => 'Daiquiri\AdminBundle\Entity\Place',
                    'property' => 'title',
                    'label' => 'Place To'
                ))
                ->add('endtime', 'sonata_type_datetime_picker', array(
                    'label' => 'Drop-off Time',
                    'attr' => array('class' => 'form-control'),
                    'required' => false))
                ->add('reverse')
                ->end()
                ->with('Transfer Exclusive Block', array('class' => 'col-md-4'))
                ->add('price0102', 'money', array('currency' => 'USD', 'label' => 'Price For 1-2 Paxs'))
                ->add('price0304', 'money', array('currency' => 'USD', 'label' => 'Price For 3-4 Paxs'))
                ->add('price0507', 'money', array('currency' => 'USD', 'label' => 'Price For 5-7 Paxs'))
                ->add('price0812', 'money', array('currency' => 'USD', 'label' => 'Price For 8-12 Paxs'))
                ->add('price1319', 'money', array('currency' => 'USD', 'label' => 'Price For 13-19 Paxs'))
                ->add('price2030', 'money', array('currency' => 'USD', 'label' => 'Price For 20-30 Paxs'))
                ->add('price3140', 'money', array('currency' => 'USD', 'label' => 'Price For 31-40 Paxs'))
                ->end()
                ->with('Product Property')
                ->add('provider', 'sonata_type_model', array(
                    'class' => 'Daiquiri\AdminBundle\Entity\Provider'
                ))
                ->add('productIncrement', 'sonata_type_model', array(
                    'class' => 'Daiquiri\AdminBundle\Entity\ProductIncrement',
                    'label' => 'Increment',
                ))
                ->add('stop')
                ->add('priority')
                ->add('available')
                ->add('payonline')
                ->add('reviewAvailable')
                
                ->end()
                ->with('Terms & Conditions', array('class' => 'col-md-4'))
                ->add('term_condition_product', 'sonata_type_model', array(
                    'class' => 'Daiquiri\AdminBundle\Entity\TermConditionProduct',
                    'property' => 'title'
                ))
                ->end()
                ->with('Cancelations Politics', array('class' => 'col-md-4'))
                ->add('cancelation_product', 'sonata_type_model', array(
                    'class' => 'Daiquiri\AdminBundle\Entity\CancelationProduct',
                    'property' => 'title'
                ))
                ->end()
                ->with('Required Documents', array('class' => 'col-md-4'))
                ->add('documents', 'sonata_type_model', array(
                    'class' => 'Daiquiri\AdminBundle\Entity\Document',
                    'property' => 'title',
                    'multiple' => true,
                    'by_reference' => false
                ))
                ->end()
                ->with('Remarks Block')
                ->add('remarks', 'sonata_simple_formatter_type', array(
                    'label' => 'Aditional Remarks',
                    'format' => 'richhtml'
                ))
                ->end()
                ->with('Tags')
                ->add('tags', 'sonata_type_model', array(
                    'class' => 'Daiquiri\AdminBundle\Entity\Tag',
                    'property' => 'title',
                    'multiple' => true,
                    'by_reference' => false
                ))
                ->end()
                ->with('Locale Block')
                ->add('locale', 'language', array(
                    'preferred_choices' => array('en', 'es', 'it')
                ))
                ->end()
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper) {
        $datagridMapper
                ->add('title', null, array('label' => 'Transfer Name'))
                ->add('placefrom', null, array('label' => 'Place From'))
                ->add('placeto', null, array('label' => 'Place To'))
                ->add('priority', null, array(), 'sonata_type_filter_number')
                ->add('available')
                ->add('payonline')
                ->add('provider')
                ->add('price0102', null, array('currency' => 'USD', 'label' => 'Price For 1-2 Paxs'), 'sonata_type_filter_number')
                ->add('price0304', null, array('currency' => 'USD', 'label' => 'Price For 3-4 Paxs'), 'sonata_type_filter_number')
                ->add('price0507', null, array('currency' => 'USD', 'label' => 'Price For 5-7 Paxs'), 'sonata_type_filter_number')
                ->add('price0812', null, array('currency' => 'USD', 'label' => 'Price For 8-12 Paxs'), 'sonata_type_filter_number')
                ->add('price1319', null, array('currency' => 'USD', 'label' => 'Price For 13-19 Paxs'), 'sonata_type_filter_number')
                ->add('price2030', null, array('currency' => 'USD', 'label' => 'Price For 20-30 Paxs'), 'sonata_type_filter_number')
                ->add('price3140', null, array('label' => 'Price For 31-40 Paxs'), 'sonata_type_filter_number')

        ;
    }

    protected function configureListFields(ListMapper $listMapper) {
        $listMapper
                //->add('picture', 'string', array('template' => 'SonataMediaBundle:MediaAdmin:list_image.html.twig'))
                //->addIdentifier('title', 'text', array('label' => 'Transfer Exclusive'))
                ->add('placefrom', null, array('label' => 'Place From', 'editable' => true))
                ->add('placeto', null, array('label' => 'Place To', 'editable' => true))
                ->add('price0102', null, array('currency' => 'USD', 'label' => '1-2', 'editable' => true))
                ->add('price0304', null, array('currency' => 'USD', 'label' => '3-4', 'editable' => true))
                ->add('price0507', null, array('currency' => 'USD', 'label' => '5-7', 'editable' => true))
                ->add('price0812', null, array('currency' => 'USD', 'label' => '8-12', 'editable' => true))
                ->add('price1319', null, array('currency' => 'USD', 'label' => '13-19', 'editable' => true))
                ->add('price2030', null, array('currency' => 'USD', 'label' => '20-30', 'editable' => true))
                ->add('price3140', null, array('currency' => 'USD', 'label' => '31-40', 'editable' => true))
                ->add('available', null, array('editable' => true))
                ->add('payonline', null, array('editable' => true))
                ->add('priority', null, array('editable' => true))
                ->add('provider')
                ->add('getFromprice')
                ->add('_action', 'actions', array(
                    'actions' => array(
                        'edit' => array(),
                        'delete' => array(),
                        
                        'apply' => array(
                            'template' => 'DaiquiriReservationBundle:Transfer:request_buttom.html.twig'
                        ),
                        'form-transfer-colective-item' => array(
                            'template' => 'DaiquiriReservationBundle:Default:book.html.twig'
                        ),
                    )
                ))
        ;
    }

    public $supportsPreviewMode = true;

    public function prePersist($object) {
        $object->setTitle($object . "");
        $object->setDescription($object . "");
    }

    public function preUpdate($object) {
        $object->setTitle($object . "");
        $object->setDescription($object . "");
    }

}
