imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: sonata.yml }
    - { resource: sonata_services.yml }
    - { resource: sonata_twig.yml }
    #- { resource: sonata_classification.yml }
    - { resource: sonata_media.yml }
    #- { resource: "comment.yml" }
    - { resource: "hwi_oauth.yml" }    

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    locales: [ 'en', 'es', 'it' ]

framework:
    session:
        gc_probability: 0
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        #form:
            #resources:
                 #- 'DaiquiriAdminBundle:Form:findautocomplete.html.php'
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataMediaBundle:Form:media_widgets.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'DaiquiriAdminBundle:Form:minmaxinput.html.twig'
            - 'DaiquiriAdminBundle:Form:findautocomplete.html.twig'
            - 'SonataFormatterBundle:Form:formatter.html.twig'
    globals:
        market: '@market'
        pagerfanta_opts:
            previous_message: '&laquo;'
            next_message:     '&raquo;'
            dots_message:     ' … '
        lang:
            locale: %locale%
            locales: %locales%
           

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false    
    bundles: [ DaiquiriAdminBundle, DaiquiriReservationBundle , DaiquiriSiteBundle ]



    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"

# Swiftmailer Configuration
swiftmailer:   
    spool:     { type: memory }

#be_simple_i18n_routing: ~

jms_i18n_routing:
    default_locale: %locale%
    locales: %locales%
    strategy: prefix 
    #prefix_except_default
 
jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            #output_dir: %kernel.root_dir%/Resources/translations
            output_dir: %kernel.root_dir%/../src/Daiquiri/SiteBundle/Resources/translations
            ignored_domains: [routes]
            excluded_names: ["TestCase.php", "Test.php", "*yml.~"]
            excluded_dirs: [cache, data, logs]
            extractors: [alias_of_the_extractor]
            #locales: [ "en", "es", "it" ] /ver como se pone esto

genemu_form:
    select2:
        enabled: true
        configs:
            placeholder: Select a value
            width: off
            allowClear: true
            minimumInputLength: 0
            
white_october_pagerfanta:
    exceptions_strategy:
        out_of_range_page:        ~
        not_valid_current_page:   ~


fos_js_routing:
    routes_to_expose: [ daiquiri_reservation_plus_for_by_hotel_and_diet,reservation_cart_delete_item_by_id,daiquiri_reservation_searcher_get_find_all,daiquiri_admin_set_current_currency,daiquiri_admin_get_market_availables,daiquiri_admin_set_current_market, check_username, check_valid_email, admin_daiquiri_admin_hotel_set-hotel-room-availability, admin_daiquiri_admin_hotel_set-hotel-room-availability-range, admin_daiquiri_admin_rentalhouse_set-rentalhouse-room-availability,daiquiri_admin_load_form_hotel_price, daiquiri_admin_get_all_season_by_room, apply-rentalhouse, apply-package,set_positive_vote, set_negative_vote,apply-circuit,admin_daiquiri_admin_circuit_set-circuit-availability,apply-medical,apply-transfer-exclusive,apply-transfer-colective, apply-car, apply-excursion-colective, apply-excursion-exclusive, admin_daiquiri_admin_car_set-car-availability, daiquiri_admin_get_block_info, admin_daiquiri_reservation_sale_get-view-all-sales,set_hotel_price_to_campaign_hotel]

