hwi_oauth:
    http_client:
         #proxy: "127.0.0.1:8080"
    connect:
        account_connector: my_user_provider
        #confirmation: true
        account_connector: hwi_oauth.user.provider.fosub_bridge
        #registration_form_handler: hwi_oauth.registration.form.handler.fosub_bridge
        #registration_form: fos_user.registration.form
    firewall_names:        [main]
    resource_owners:
        facebook:
            type:          facebook
            client_id:     %facebook_app_id%
            client_secret: %facebook_app_secret%
            scope:         "email"
            infos_url:     "https://graph.facebook.com/me?fields=id,name,email,picture.type(square)"
            paths:
                email:     email
                profilepicture: picture.data.url
            options:
                display:    popup
        twitter:
            type:                twitter
            client_id:           %twitter_app_id%
            client_secret:       %twitter_app_secret%
            infos_url:           "https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true"
            paths:
                email: email
#            options:
#                include_email: true
#        twitter:
#            type:          twitter
#            client_id:     %twitter_app_id%
#            client_secret: %twitter_app_secret%
#            infos_url:      "https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true"
#            scope:         ""
#            paths:
#                email: email
#            options:
#                include_email: true
        google:
            type:                google
            client_id:           "%google_app_id%"
            client_secret:       "%google_app_secret%"
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            paths:
                email:           email
                profilepicture:  picture
            
    fosub:
        # try 30 times to check if a username is available (foo, foo1, foo2 etc)
        username_iterations: 30        
        # mapping between resource owners (see below) and properties
        properties:
            facebook: facebook_id
            twitter: twitter_id
            gmail: gmail_id
            